on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone env config repository
        run: git clone git@github.com:Kenechukwu-YV/femi_env.git

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg ENV_FILE=femi_env/.env \
            -t "${{ env.IMAGE_NAME }}:latest" \
            .
          docker push ${{ env.DOCKER_HUB_USERNAME }}/calorypal:v2